[org/gnome/shell/extensions/simple-weather]
always-packaged-icons=false
is-activated=true
locations=['{"name":"Madrid","lat":40.4168,"lon":-3.7038}']
main-location-index=0
my-loc-provider='ipapi.co'
panel-box='left'
secondary-panel-detail='conditionText'
show-panel-icon=true
show-suntime=false
symbolic-icons-panel=true

